### ISSUE TITLE
File "get_distance.py", line 52, in <lambda>     x = Lambda(lambda  x_: K.l2_normalize(x,axis=1))(x) NameError: name 'K' is not defined

### ISSUE THREAD

**Issue by ajaxrays21** [USCDataScience/Image-Similarity-Deep-Ranking#3]
File "get_distance.py", line 52, in <lambda>
    x = Lambda(lambda  x_: K.l2_normalize(x,axis=1))(x)
NameError: name 'K' is not defined

**Comment by Purvak-L** [comment]
Hey,
Use - from keras import backend as K
I've merged changes to master branch.
Thank you for pointing it out
